package model.digital;

import model.Title;

public abstract class NetTitle extends Title {
    private int availability; // Antal kommuner, der har udlånt bogen
    private int reach; // Antal kommuner, der har bogen til udlån
    private int use; // Antal udlån

    public NetTitle(String title, String literatureType, int availability, int reach, int use) {
        super(title, literatureType);
        this.availability = availability;
        this.reach = reach;
        this.use = use;
    }

    protected double calculateNetPoints(double calculatedPagesOrDuration){
        return calculatedPagesOrDuration * convertLiteratureType() *
                ((reach * 5) + (availability * 0.5) + getUseFactor());
    }

    public int getUseFactor() {
        if (this.use <= 25) return 0;
        if (this.use <= 75) return 50;
        if (this.use <= 150) return 100;
        if (this.use <= 400) return 150;
        if (this.use <= 1000) return 200;
        if (this.use <= 2000) return 250;
        if (this.use <= 5000) return 500;
        if (this.use <= 10000) return 750;
        return 1000;

        // Generated by ChatGPT, just a prettier if statement.
    }

    public int getAvailability() {
        return availability;
    }

    public int getReach() {
        return reach;
    }
}
